### ISSUE TITLE
Finally doesn't work as expected

### ISSUE THREAD

**Issue by rsoesemann** [ruslan-kurchenko/sfdc-lax#10]
When I do 

```
      cmp.lax.enqueue("c.saveAndDistribute", { changesJson: JSON.stringify(volumeAggregates) })
            .catch((e) => {
                cmp.find("toast").toastError(e);
            })
            .then(() => {
                cmp.find("spinner").hide();
            });
```

it works as expected, but not when I use finally(). The spinner is not hidden in the error case.

```
      cmp.lax.enqueue("c.saveAndDistribute", { changesJson: JSON.stringify(volumeAggregates) })
            .catch((e) => {
                cmp.find("toast").toastError(e);
            })
            .finally(() => {
                cmp.find("spinner").hide();
            });
```

**Comment by ruslan-kurchenko** [comment]
@up2go-rsoesemann did you resolve the issue? What was the problem?

**Comment by rsoesemann** [comment]
I didn't understand the `(...) => {}` construct and tried finally without it. Just that. Which didn't work.
```
             ...
            .finally({
                cmp.find("spinner").hide();
            });
```

What is it by the way??

**Comment by ruslan-kurchenko** [comment]
@up2go-rsoesemann It is *Arrow Function* expression. It was introduced with ECMAScript 6. Basically, it is much easier to assign callback using arrow functions. There are some specific things that are different from common functions.

Here is doc: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions
