### ISSUE TITLE
[extension] Make LAX code "compliant" with Lightning Linter

### ISSUE THREAD

**Issue by rsoesemann** [ruslan-kurchenko/sfdc-lax#15]
When I run the Lightning Lint over my Lax-ed components many errors are detected. Maybe the linter is a bit stupid but maybe there are some tricks how you can make you code fly under the Linter radar ;-)

<img width="726" alt="cprm____dev_projects_cprm__-_____src_aura_addopwindow_addopwindowcontroller_js__cprm_" src="https://user-images.githubusercontent.com/8180281/35965245-8a865e4e-0cba-11e8-9448-75be8d7fe44b.png">

**Comment by ruslan-kurchenko** [comment]
@rsoesemann nice point! Thank you!

**Comment by ruslan-kurchenko** [comment]
Released in v1.2.1
