### ISSUE TITLE
[bug] this._contextPromise.finally is not a function in Firefix 47 (not in 48)

### ISSUE THREAD

**Issue by rsoesemann** [ruslan-kurchenko/sfdc-lax#16]
<img width="584" alt="skype_png" src="https://user-images.githubusercontent.com/8180281/36035901-a29e62fc-0db8-11e8-95f7-160a93e647af.png">

**Comment by ruslan-kurchenko** [comment]
@rsoesemann is it working in Chrome/Safari?

**Comment by rsoesemann** [comment]
Yes!

**Comment by ruslan-kurchenko** [comment]
Got it. I will watch on that asap. Thank you!

**Comment by ruslan-kurchenko** [comment]
@rsoesemann 
I would guess that Firefox is not compatible with `Promise.prototype.finally` function:
See answer - https://stackoverflow.com/questions/22516959/how-to-determine-if-a-promise-is-supported-by-the-browser
Also, the link to the Firefox releases - https://wiki.mozilla.org/RapidRelease/Calendar
Release date: _2016-01-25_
As soon as in the answer on StackOverflow:
_Update Nov 14 - 2016: Chrome, Firefox, Safari and IE all now have experimental support for promises in their dev channels. The specification has settled. I would still not rely on the implementation just yet and would use a library but this might change in a few months._

Do you have client that still work on this old version?

**Comment by ruslan-kurchenko** [comment]
`Promise.prototype.finally` is part of _ES2016+_. And unfortunatelly it is not compatible with Firefox 47.
<img width="499" alt="screen shot 2018-02-09 at 7 05 26 pm" src="https://user-images.githubusercontent.com/29373749/36039911-8c97f4aa-0dcc-11e8-9d56-45bdd26f5f76.png">

**Comment by rsoesemann** [comment]
Thanks for digging in so deep. Yes we have a customer using this browser but this is enough material to convince him to upgrade. I hope...

**Comment by rsoesemann** [comment]
Anychance for us to work around this on customers who stay on a shitty ff version? We use your lib everywhere 😬

**Comment by rsoesemann** [comment]
Is this also a problem with standard salesforce promises? If so it should be excluded from salesforce supported browsers. Is it?

**Comment by ruslan-kurchenko** [comment]
I’ll investigate that deeper. Maybe there is a chance to use polyfill. Stay tuned.

**Comment by ruslan-kurchenko** [comment]
@rsoesemann ok, there is available implementation for situation like we have. 
https://www.npmjs.com/package/promise.prototype.finally
I’ll try to use that lib, I think.

**Comment by rsoesemann** [comment]
That would be a workaround for the FF 47 issue? Good luck.

**Comment by ruslan-kurchenko** [comment]
Yep, that would be a workaround for all browsers that do not support Promise.prototype.finally
I hope to simplify that, cuz this lib has a lot of logic. It may be an overhead for the component

**Comment by rsoesemann** [comment]
Otherwise I have to remove lax from the product 😰

**Comment by ruslan-kurchenko** [comment]
I'll try to fix that. In another case, you could avoid of `.finally` usage. Or use `LaxActionBuilder` which doesn't rely on Promise API

**Comment by rsoesemann** [comment]
When you say I can use `LaxActionBuilder` does this mean I can use its newly released "finally" as well?

**Comment by ruslan-kurchenko** [comment]
@rsoesemann exactly!
See `.finallyCallback`. The is the simple function without any Promise API logic.

https://github.com/ruslan-kurchenko/sfdc-lax/blob/de46fac92e72b33ddcbed9295028ea998dbf0fe3/src/aura/lax/laxHelper.js#L89-L119

**Comment by ruslan-kurchenko** [comment]
@rsoesemann just released v1.2.2 with `Promise.prototype.finally` polyfill for non-compatible browsers. 
I've tested on the FF47 and that is working fine.
See `examples` branch with tests: https://github.com/ruslan-kurchenko/sfdc-lax/blob/examples/src/aura/PromiseFinallyComponent/PromiseFinallyComponentController.js

**Comment by ruslan-kurchenko** [comment]
@rsoesemann let me know if something went wrong with this update.

**Comment by rsoesemann** [comment]
Thanks a lot. I will test tommorow.

**Comment by rsoesemann** [comment]
It worked. You are AWESOME.
