### ISSUE TITLE
How to JS-throw error in then() to be catched in catch()

### ISSUE THREAD

**Issue by rsoesemann** [ruslan-kurchenko/sfdc-lax#17]
I have a use case that is not easy to handle with AuraHandledExceptions alone. Before I query a lot of records in Apex I first count them. Depending on the resultCount I want the below JS code to eighter fire a new callback or throw the same type of error that an Apex side exception would have thrown. Why? So I can handle it with the same LAX catch.

Is that possible?

```
 cmp.lax.enqueue("c.countResults")
    .then((resultCount) => {
        if(resultCount < 1000)
            return cmp.lax.enqueue("c.queryData");
        }
        else {
            // Throw error to be catched and display in below catch
        }
    })
    .then((result) => {
        ...
    })
    .catch((e) => {
        cmp.find("toast").toastError(e);
    });
```

**Comment by rsoesemann** [comment]
I was able to solve this by simply doing `throw 'message';` But the message was always prefixed with `"Error in $A.getCallback() []"`. So I had to replace the error.message. 

Maybe there is a better way.


```
 cmp.lax.enqueue("c.countResults")
    .then((resultCount) => {
        if(resultCount < 1000)
            return cmp.lax.enqueue("c.queryData");
        }
        else {
            throw 'error message';
        }
    })
    .catch((e) => {
        e.message = e.message.replace("Error in $A.getCallback() [", "").replace("]", "");
        cmp.find("toast").toastError(e);
    });
```

**Comment by ruslan-kurchenko** [comment]
Hi, @rsoesemann! Excuse me, I didn't get a notification about this issue.
The thing is that `.catch()` handle `$A.getCallback()` function, that is why it displays this concatenated message, I think so... :)
You could try to add that same logic in Lax code and create PR for that.
Or I'll solve that. But I can start work on that after 1-2 weeks, unfortunately. It should be easy to handle.

**Comment by ruslan-kurchenko** [comment]
@rsoesemann
 
https://github.com/ruslan-kurchenko/sfdc-lax/blob/76ea2518d749923697f692869cd5cbbf7b4915b5/src/aura/lax/laxHelper.js#L174-L189

`routeError()` function is the first handler in the chain, you could try to add your logic there.

**Comment by rsoesemann** [comment]
Just in case you wonder what I did. I decided to wait until you implement. Better an elegant solution later than a quickhack now ;-)

**Comment by ruslan-kurchenko** [comment]
@rsoesemann I've completed this item :) Could you help me to test that on your side?

Here is feature branch with this particular change: https://github.com/ruslan-kurchenko/sfdc-lax/tree/feature/remove-aura-error-message-prefix

**Comment by rsoesemann** [comment]
Works like a charm.
