### ISSUE TITLE
Cannot define property lax, object is not extensible

### ISSUE THREAD

**Issue by nilvon9wo** [ruslan-kurchenko/sfdc-lax#2]
Hi,
I'm just trying this out for the first time, but it isn't working as expected.

Instead the page fails to render and I get the following error message:
`Uncaught Action failed: c:lax$controller$onInit [Cannot define property lax, object is not extensible]
Callback failed: serviceComponent://ui.flexipage.components.page.FlexipageControllerV2/ACTION$getPage
`

This is the stack trace:
`Object.init()@https://th15-dev-ed.lightning.force.com/one/components/c/lax.js:39:12
onInit()@https://th15-dev-ed.lightning.force.com/one/components/c/lax.js:10:12`

If it helps, I'm trying to adapt code from a [trailhead](https://trailhead.salesforce.com/trails/microsoft_dotnet/projects/transform-sql-queries-to-soql-queries-in-a-lightning-app/steps/write-your-first-soql-query)

This is my markup:
`<aura:component access="global" controller="Books4EveryoneHomeAuraCtrl" implements="flexipage:availableForAllPageTypes">
	<c:lax context="{!this}" />
	
	<aura:attribute name="bookList" type="Book__c[]" />
	<aura:handler name="init" action="{!c.doInit}" value="{!this}" />
	
	<lightning:card title="Books4Everyone Books">
		<table class="slds-table slds-table_bordered slds-table_cell-buffer">
			<thead>
				<tr class="slds-text-title_caps">
					<th scope="col">Book Titles</th>
					<th scope="col">Book Descriptions</th>
				</tr>
			</thead>
			<tbody>
				<aura:iteration items="{!v.bookList}" var="book">
					<tr scope="row">
						<td>{!book.Name}</td>
						<td>{!book.Description__c}</td>
					</tr>
				</aura:iteration>
			</tbody>
		</table>
	</lightning:card>
</aura:component>
`

and this is my controller:
`({
	doInit : function(component, event, helper) {
		component.lax.enqueue('c.getBooks')
			.then(bookList => {
				component.set('v.bookList', bookList);
			});
	}
})`

**Comment by ruslan-kurchenko** [comment]
Hey @nilvon9wo! Thanks for the reply. Let me reproduce a problem and I will be back to you so stay tuned.

**Comment by ruslan-kurchenko** [comment]
@nilvon9wo I have completed the trailhead you shared and everything works ok for me.
I'm using Chrome - `Version 63.0.3239.84 (Official Build) (64-bit)`
What browser do you use? 
Did you make any specific settings on your Salesforce ORG?

Below is the code I've created:

*Apex Controller:*
```
public with sharing class Books4EveryoneHomeController { 
  @AuraEnabled 
  public static List<Book__c> getBooks(){ 
    return [SELECT Id,Name,Description__c FROM Book__c];
  } 
}
```

*Component Markup:*
```
<aura:component implements="flexipage:availableForAllPageTypes" access="global" controller="Books4EveryoneHomeController"> 
  <c:lax context="{!this}" />
    
  <aura:attribute name="bookList" type="Book__c[]" /> 
  <aura:handler name="init" action="{!c.doInit}" value="{!this}"/> 
  <lightning:card title="Books4Everyone Books"> 
    <aura:set attribute="body"> 
      <table class="slds-table slds-table_bordered slds-table_cell-buffer"> 
        <thead>
          <tr class="slds-text-title_caps"> 
            <th scope="col">Book Titles</th> 
            <th scope="col">Book Descriptions</th> 
          </tr> 
        </thead> 
        <tbody> 
          <aura:iteration items="{!v.bookList}" var="book"> 
            <tr scope="row"> 
              <td> {!book.Name}</td> 
              <td> {!book.Description__c}</td> 
            </tr> 
          </aura:iteration> 
        </tbody> 
      </table> 
    </aura:set> 
  </lightning:card> 
</aura:component>
```

*Component JavaScript Controller:*
```
({ 
  doInit: function(component, event, helper) { 
    component.lax.enqueue('c.getBooks') 
    	.then(bookList => { 
            console.log('bookList', bookList);
            component.set('v.bookList', bookList); 
        });
  } 
}) 
```

**Comment by ruslan-kurchenko** [comment]
@nilvon9wo did you resolve the problem?

**Comment by ruslan-kurchenko** [comment]
The workflow is not reproduced. @nilvon9wo I will close the issue due to inactivity. Please, contact me if you reach out the problem again. Thanks!

**Comment by kacrouse** [comment]
I ran into this issue also. After some experimentation, I determined that it occurs if you are using `lax` in a component on an API version prior to `40.0`.

**Comment by ruslan-kurchenko** [comment]
@kacrouse thank you for reaching out! I'll try your suggestion asap and let you know
