### ISSUE TITLE
Add a flag to automatically `JSON.parse` response from Apex

### ISSUE THREAD

**Issue by kvizcarra** [ruslan-kurchenko/sfdc-lax#20]
We return a JSON-serialized Map of data from all our `@AuraEnabled` methods and were `JSON.parse`ing the response in our custom Apex callout component. Now that we've switched to Lax we have to append a `.then(JSON.parse)` to all our Lax calls. It's not a big deal but it's really easy to forget. It would be nice if there was a flag we could set either in a component attribute, ala `v. attributeName`, or in the `options` object passed to `component.lax.enqueue()`.

**Comment by ruslan-kurchenko** [comment]
@kvizcarra sounds nice to me! I'll investigate it.

**Comment by ruslan-kurchenko** [comment]
Merged into #21
