### ISSUE TITLE
"Freeze JavaScript Prototypes" Session Setting in Winter '19 breaks Lax

### ISSUE THREAD

**Issue by kvizcarra** [ruslan-kurchenko/sfdc-lax#24]
In Winter '19, there's a new Session Setting called **Freeze JavaScript Prototypes** that prevents the modification of prototypes. When this setting is enabled, Lax will fail to initialize.

![lax-error](https://user-images.githubusercontent.com/25014586/45896172-29d7a380-bd88-11e8-9aee-c3e2e0f8f2ec.png)
![lax-error-in-code](https://user-images.githubusercontent.com/25014586/45896171-29d7a380-bd88-11e8-9180-4d4ef3741847.png)

**Comment by ruslan-kurchenko** [comment]
@kvizcarra, thank you for noticing it!
I'll work on it asap to avoid `Prototype` modifications.

**Comment by ruslan-kurchenko** [comment]
@kvizcarra, could you test the latest update? I've tested it on Summer 18 + Locker Console and it works as before. The only distinction is that the constructor if the Error is a default.

**Comment by douglascayers** [comment]
Hi @ruslan-kurchenko, are your prototype updates for Winter '19 in testing or is that supposed to be a new version? Looking at the [Releases](https://github.com/ruslan-kurchenko/sfdc-lax/releases) tab, these changes are not yet in a "version". I'm wanting to use LAX in [Mass Action Scheduler](https://github.com/douglascayers/sfdx-mass-action-scheduler) and wasn't sure which "version" I should say I'm using in my project.

Thanks!

**Comment by ruslan-kurchenko** [comment]
Hey, @douglascayers!
I've created a release with this particular update - [v1.2.5](https://github.com/ruslan-kurchenko/sfdc-lax/releases/tag/v1.2.5)

I was waiting for the testing result from @kvizcarra as soon as he is the person how suggested this update.
Nevertheless, I've tried these changes on the Winter 19 org and it works as expected.

Please, let me know if everything works as expected with Prototypes. Then I'll close this ticket.

And thank you for choosing LAX for Mass Action Scheduler! 👍

**Comment by kvizcarra** [comment]
@ruslan-kurchenko Sorry for such a late reply. I confirmed the latest changes are working. Thank you!

**Comment by ruslan-kurchenko** [comment]
@kvizcarra Awesome, thank you!
