### ISSUE TITLE
Add record reload method to LDS helper

### ISSUE THREAD

**Issue by sjurgis** [ruslan-kurchenko/sfdc-lax#25]
It seems that LDS doesn't automatically load records on recordId change - you need to execute reloadRecord method, which takes in callback.

My use case is convert lead, load Opportunity and Account, throw some data there...

**Comment by ruslan-kurchenko** [comment]
Hi @sjurgis, could you provide more information with code examples to collaborate on your suggestion?

**Comment by sjurgis** [comment]
Sorry I gave up on using LDS :)
IIRC passing recordId to LDS wasn't really reacting to Id change, so I had to use reloadRecord method. Could be mistaken tho.

**Comment by ruslan-kurchenko** [comment]
@sjurgis I had a similar issue and I moved from LDS that time...
