### ISSUE TITLE
Recommended Migration to Lightning Web Components

### ISSUE THREAD

**Issue by rsoesemann** [ruslan-kurchenko/sfdc-lax#26]
I am in the process of migration a few douzens of Aura-based components to LWC. All of them used LAX for their callback handling. What do you propose how to migrate them.

**Just stop using Lax because LWC solves everything natively or keep stuff?**

**Comment by ruslan-kurchenko** [comment]
@rsoesemann, I haven't thought about it too much yet.
Basically, LAX is covering a lack of functionality that LWCs cover. There is additional functionality which is less commonly used, but I would suggest defining new utilities for it. You even can copy things from this repo if you need...
Anyway, if you have any suggestions, please provide them. The thing is that currently I don't work with LWCs and do not have too much time to cover it.

**Comment by rsoesemann** [comment]
I will go on with my migration and collect use cases where I missed lax. And report back to you.

**Comment by ruslan-kurchenko** [comment]
Thank you, @rsoesemann! I appreciate it 🤝
