### ISSUE TITLE
Error overriding Promise prototype methods when "Freeze JavaScript Prototypes" is on

### ISSUE THREAD

**Issue by craigdor** [ruslan-kurchenko/sfdc-lax#28]
Salesforce has extended the "Freeze JavaScript Prototypes" feature (https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/security_freeze_prototypes.htm) to include the Promise object.
This causes an error like "Cannot assign to read only property 'then' of object '[object Promise]' " when trying to override the Promise.prototype methods with LaxPromise methods.

![image](https://user-images.githubusercontent.com/36900790/69568926-74971180-0f71-11ea-97b1-d76a5710cc2d.png)
![image](https://user-images.githubusercontent.com/36900790/69569212-03a42980-0f72-11ea-8710-1082ad304f1d.png)

**Comment by ruslan-kurchenko** [comment]
Closing the issue as it is resolved by @craigdor

**Comment by sjurgis** [comment]
@ruslan-kurchenko FYI setting has been removed https://releasenotes.docs.salesforce.com/en-us/spring20/release-notes/rn_lc_locker_remove_freeze.htm
